import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "@/app/globals.css";
import CartProvider from "@/components/cart/provider";
import { Toaster } from "@/components/ui/sonner";
import Navbar from "@/components/ui/navbar";

const inter = Inter({ subsets: ["latin"] });
export const metadata: Metadata = {
    title: "Create Next App",
    description: "Generated by create next app",
};

export default function RootLayout({
    children,
}: Readonly<{
    children: React.ReactNode;
}>) {
    return (
        <html lang="en">
            <body className={inter.className}>
                <CartProvider>
                    <Navbar></Navbar>
                    {children}
                </CartProvider>
                <Toaster></Toaster>
            </body>
        </html>
    );
}
